const char *upath = "/dev/uinput";

struct map bindings[] = {
	{ CEC_USER_CONTROL_CODE_EXIT,    KEY_Q },
	{ CEC_USER_CONTROL_CODE_SELECT,  KEY_ENTER },
	{ CEC_USER_CONTROL_CODE_UP,      KEY_UP },
	{ CEC_USER_CONTROL_CODE_DOWN,    KEY_DOWN },
	{ CEC_USER_CONTROL_CODE_LEFT,    KEY_LEFT },
	{ CEC_USER_CONTROL_CODE_RIGHT,   KEY_RIGHT },
	{ CEC_USER_CONTROL_CODE_NUMBER0,   KEY_0 },
	{ CEC_USER_CONTROL_CODE_NUMBER1,   KEY_1 },
	{ CEC_USER_CONTROL_CODE_NUMBER2,   KEY_2 },
	{ CEC_USER_CONTROL_CODE_NUMBER3,   KEY_3 },
	{ CEC_USER_CONTROL_CODE_NUMBER4,   KEY_4 },
	{ CEC_USER_CONTROL_CODE_NUMBER5,   KEY_5 },
	{ CEC_USER_CONTROL_CODE_NUMBER6,   KEY_6 },
	{ CEC_USER_CONTROL_CODE_NUMBER7,   KEY_7 },
	{ CEC_USER_CONTROL_CODE_NUMBER8,   KEY_8 },
	{ CEC_USER_CONTROL_CODE_NUMBER9,   KEY_9 },
};
